// (Disabled) HTTP Function End-to-End Test Template
// Purpose: Illustrative placeholder showing how to test an HTTP-triggered generation path.
// To enable: uncomment, ensure emulator running, and adjust PROJECT_ID/bucket names.
//
// import { expect } from 'chai';
// import admin from 'firebase-admin';
// import fetch from 'node-fetch';
// import * as cheerio from 'cheerio';
//
// const PROJECT_ID = 'astro-gcp-builder-test-182e3';
// const SOURCE_BUCKET_NAME = 'your-source-json-bucket';
// const DEST_BUCKET_NAME = 'your-final-static-site-bucket';
// const FUNCTION_URL = `http://127.0.0.1:5001/${PROJECT_ID}/us-central1/handler`;
//
// process.env.FIREBASE_STORAGE_EMULATOR_HOST = 'localhost:9199';
// admin.initializeApp({ projectId: PROJECT_ID, storageBucket: SOURCE_BUCKET_NAME });
//
// const sourceBucket = admin.storage().bucket(SOURCE_BUCKET_NAME);
// const destBucket = admin.storage().bucket(DEST_BUCKET_NAME);
//
// describe('HTTP Triggered Site Generation (E2E)', function() {
//   this.timeout(30000);
//
//   before(async () => {
//     await sourceBucket.deleteFiles({ force: true });
//     await destBucket.deleteFiles({ force: true });
//   });
//
//   it('generates and uploads the correct HTML when the HTTP function is called', async () => {
//     const testPost = [{
//       slug: 'e2e-final-test',
//       title: 'This is the E2E Test Title',
//       author: 'E2E Bot',
//       content: 'This content was generated by an automated test.'
//     }];
//     const testFileName = 'e2e-trigger.json';
//     await sourceBucket.file(testFileName).save(JSON.stringify(testPost));
//
//     const response = await fetch(FUNCTION_URL, {
//       method: 'POST',
//       headers: { 'Content-Type': 'application/json' },
//       body: JSON.stringify({ pathToLargeJsonFile: testFileName }),
//     });
//     expect(response.status).to.equal(200);
//
//     const finalHtmlPath = `posts/${testPost[0].slug}/index.html`;
//     const [fileContents] = await destBucket.file(finalHtmlPath).download();
//     const $ = cheerio.load(fileContents.toString());
//     expect($('h1').text()).to.equal('This is the E2E Test Title');
//   });
// });
